name: plant_monitoring
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  getwidget: ^4.0.0
  google_fonts: ^5.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_auth_platform_interface: ^7.1.8
  firebase_database: ^10.4.9
  time_picker_spinner_pop_up: ^2.0.0
  day_night_time_picker: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
